/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 5.0 */
package com.zookitec.layout.source.parser;

public interface ExpressionParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTMETHODCALL = 2;
  public int JJTPARAMETER = 3;
  public int JJTNUMBER = 4;
  public int JJTARRAY = 5;
  public int JJTCOMPONENTNAME = 6;
  public int JJTMETHODNAME = 7;


  public String[] jjtNodeName = {
    "start",
    "expression",
    "methodCall",
    "parameter",
    "number",
    "array",
    "componentName",
    "methodName",
  };
}
/* JavaCC - OriginalChecksum=e2612e8a50498e9ced34171e64a886da (do not edit this line) */
